const ActionTypes = {
  UPDATE_EDF: 'UPDATE_EDF',
  UPDATE_PERSON: 'UPDATE_PERSON',
  ATTACH_WITNESS: 'ATTACH_WITNESS',
  REQUEST_PERSONS: 'REQUEST_PERSONS',
  RECEIVE_PERSONS: 'RECEIVE_PERSONS',
  RECEIVE_PERSONS_FAILURE: 'RECEIVE_PERSONS_FAILURE',
  REQUEST_WITNESSES: 'REQUEST_WITNESSES',
  RECEIVE_WITNESSES: 'RECEIVE_WITNESSES',
  RECEIVE_WITNESSES_FAILURE: 'RECEIVE_WITNESSES_FAILURE',
  CHANGE_DATA_CREATION_VIEW: 'CHANGE_DATA_CREATION_VIEW',
  CHANGE_FOCUSED_WITNESS: 'CHANGE_FOCUSED_WITNESS',
  UPDATE_WITNESS: 'UPDATE_WITNESS',
};

export default ActionTypes;
