const ActionTypes = {
  ASSIGN_EDF: 'ASSIGN_EDF',
  ASSIGN_PERSON: 'ASSIGN_PERSON',
  ATTACH_WITNESS: 'ATTACH_WITNESS',
  REQUEST_PERSONS: 'REQUEST_PERSONS',
  RECEIVE_PERSONS: 'RECEIVE_PERSONS',
  RECEIVE_PERSONS_FAILURE: 'RECEIVE_PERSONS_FAILURE',
  REQUEST_WITNESSES: 'REQUEST_WITNESSES',
  RECEIVE_WITNESSES: 'RECEIVE_WITNESSES',
  RECEIVE_WITNESSES_FAILURE: 'RECEIVE_WITNESSES_FAILURE',
  CHANGE_DATA_CREATION_VIEW: 'CHANGE_DATA_CREATION_VIEW',
  CHANGE_FOCUSED_WITNESS: 'CHANGE_FOCUSED_WITNESS',
  UPDATE_WITNESS: 'UPDATE_WITNESS',
  CREATE_WITNESS: 'CREATE_WITNESS',
  ATTACH_WITNESS: 'ATTACH_WITNESS',
  REQUEST_EDFS: 'REQUEST_EDFS',
  RECEIVE_EDFS: 'RECEIVE_EDFS',
  RECEIVE_EDFS_FAILURE: 'RECEIVE_EDFS_FAILURE',
  CLEAR_EDF_INFO: 'CLEAR_EDF_INFO',
  CREATE_EDF: 'CREATE_EDF',
  UPDATE_EDF: 'UPDATE_EDF'

};

export default ActionTypes;
